/**
 * Station Availability — Gap Detection Proxy Signal
 *
 * Compares consecutive daily station snapshots to detect stations that
 * stopped reporting. A station present yesterday but absent today is
 * "not reporting" — a proxy for potentially being out of fuel.
 *
 * This is a structural proxy, not a confirmed outage count. Stations
 * may stop reporting for other reasons (maintenance, system errors,
 * temporary closure). The signal is most useful in aggregate and in
 * the context of other supply chain signals.
 *
 * Data sources:
 *   - WA FuelWatch (daily, ~1,100 stations across diesel + petrol)
 *   - NSW FuelCheck (daily, ~5,600 stations across diesel + petrol)
 *
 * Snapshot files: app/src/data/station-snapshots/YYYY-MM-DD.json
 * Generated by: scripts/snapshot-stations.mjs (runs in daily launchd agent)
 */

import { readFileSync, readdirSync } from "fs";
import path from "path";
import type { Signal, SignalComponent } from "./types";

const SNAPSHOT_DIR = path.join(
  process.cwd(),
  "src",
  "data",
  "station-snapshots"
);

interface StationRecord {
  id: string;
  state: string;
  source: string;
  product: string;
  brand: string | null;
  name: string;
  location: string;
  price: number;
}

interface Snapshot {
  date: string;
  generated: string;
  sources: {
    wa_fuelwatch: { diesel: number; petrol: number };
    nsw_fuelcheck: { diesel: number; petrol: number };
  };
  totalStations: number;
  stations: StationRecord[];
}

function loadSnapshot(filename: string): Snapshot | null {
  try {
    const filePath = path.join(SNAPSHOT_DIR, filename);
    const raw = readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as Snapshot;
  } catch {
    return null;
  }
}

function getSnapshotFiles(): string[] {
  try {
    return readdirSync(SNAPSHOT_DIR)
      .filter((f) => f.match(/^\d{4}-\d{2}-\d{2}\.json$/))
      .sort()
      .reverse(); // newest first
  } catch {
    return [];
  }
}

interface GapAnalysis {
  today: Snapshot;
  yesterday: Snapshot;
  stoppedReporting: StationRecord[];
  newlyReporting: StationRecord[];
  byState: Record<string, { stopped: number; new: number; todayTotal: number; yesterdayTotal: number }>;
  byProduct: Record<string, { stopped: number; new: number }>;
}

function analyseGaps(today: Snapshot, yesterday: Snapshot): GapAnalysis {
  const todayIds = new Set(today.stations.map((s) => s.id));
  const yesterdayIds = new Set(yesterday.stations.map((s) => s.id));
  const yesterdayById = new Map(yesterday.stations.map((s) => [s.id, s]));
  const todayById = new Map(today.stations.map((s) => [s.id, s]));

  const stoppedReporting: StationRecord[] = [];
  const newlyReporting: StationRecord[] = [];

  for (const id of yesterdayIds) {
    if (!todayIds.has(id)) {
      stoppedReporting.push(yesterdayById.get(id)!);
    }
  }

  for (const id of todayIds) {
    if (!yesterdayIds.has(id)) {
      newlyReporting.push(todayById.get(id)!);
    }
  }

  // Breakdown by state
  const byState: Record<string, { stopped: number; new: number; todayTotal: number; yesterdayTotal: number }> = {};
  for (const s of stoppedReporting) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].stopped++;
  }
  for (const s of newlyReporting) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].new++;
  }
  for (const s of today.stations) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].todayTotal++;
  }
  for (const s of yesterday.stations) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].yesterdayTotal++;
  }

  // Breakdown by product
  const byProduct: Record<string, { stopped: number; new: number }> = {};
  for (const s of stoppedReporting) {
    if (!byProduct[s.product]) byProduct[s.product] = { stopped: 0, new: 0 };
    byProduct[s.product].stopped++;
  }
  for (const s of newlyReporting) {
    if (!byProduct[s.product]) byProduct[s.product] = { stopped: 0, new: 0 };
    byProduct[s.product].new++;
  }

  return { today, yesterday, stoppedReporting, newlyReporting, byState, byProduct };
}

export function fetchStationAvailability(): Signal | null {
  const files = getSnapshotFiles();
  if (files.length === 0) return null;

  const today = loadSnapshot(files[0]);
  if (!today) return null;

  // If we only have one snapshot, report station counts (no gap yet)
  if (files.length < 2) {
    return {
      label: "Station availability",
      value: `${today.totalStations} reporting`,
      trend: "stable",
      source: `FuelWatch WA + FuelCheck NSW — ${today.date}`,
      sourceUrl: "https://www.fuelwatch.wa.gov.au/",
      context:
        `Monitoring ${today.totalStations} fuel stations across WA and NSW. ` +
        `WA: ${today.sources.wa_fuelwatch.diesel + today.sources.wa_fuelwatch.petrol} stations. ` +
        `NSW: ${today.sources.nsw_fuelcheck.diesel + today.sources.nsw_fuelcheck.petrol} stations. ` +
        `Gap detection requires at least two daily snapshots — first snapshot collected ${today.date}. ` +
        `Stations that stop reporting between snapshots may indicate fuel unavailability.`,
      lastUpdated: today.generated,
      automated: true,
      layer: 4,
      layerLabel: "Retail impact",
      propagatesTo:
        "Station closures compound panic buying and increase travel distance for remaining supply",
    };
  }

  const yesterday = loadSnapshot(files[1]);
  if (!yesterday) return null;

  const gaps = analyseGaps(today, yesterday);
  const stoppedCount = gaps.stoppedReporting.length;
  const newCount = gaps.newlyReporting.length;
  const netChange = newCount - stoppedCount;

  // Trend based on net disappearances
  const stoppedPct = (stoppedCount / yesterday.totalStations) * 100;
  const trend: Signal["trend"] =
    stoppedPct > 5
      ? "critical"
      : stoppedPct > 2
        ? "up"
        : stoppedCount > newCount
          ? "up"
          : "stable";

  // Components: state-level breakdown
  const components: SignalComponent[] = [];
  for (const [state, data] of Object.entries(gaps.byState)) {
    if (data.stopped > 0 || data.new > 0) {
      components.push({
        label: `${state} stations`,
        value: `${data.todayTotal} reporting`,
        change:
          data.stopped > 0
            ? `-${data.stopped} stopped${data.new > 0 ? `, +${data.new} new` : ""}`
            : `+${data.new} new`,
        trend: data.stopped > data.new ? "up" : "stable",
      });
    }
  }

  // Product breakdown
  for (const [product, data] of Object.entries(gaps.byProduct)) {
    if (data.stopped > 0) {
      components.push({
        label: `${product.charAt(0).toUpperCase() + product.slice(1)} gaps`,
        value: `${data.stopped} stopped`,
        change: data.new > 0 ? `+${data.new} returned` : undefined,
        trend: data.stopped > 5 ? "up" : "stable",
      });
    }
  }

  // Build context narrative
  let context = "";

  if (stoppedCount === 0) {
    context =
      `All ${today.totalStations} monitored stations reporting normally. ` +
      `No gaps detected between ${yesterday.date} and ${today.date}.`;
  } else {
    context =
      `${stoppedCount} station${stoppedCount !== 1 ? "s" : ""} that reported ` +
      `on ${yesterday.date} did not report on ${today.date}. `;

    if (newCount > 0) {
      context += `${newCount} station${newCount !== 1 ? "s" : ""} resumed or started reporting (net change: ${netChange > 0 ? "+" : ""}${netChange}). `;
    }

    // State detail
    const stateDetails = Object.entries(gaps.byState)
      .filter(([, d]) => d.stopped > 0)
      .map(
        ([state, d]) =>
          `${state}: ${d.stopped} stopped (${((d.stopped / d.yesterdayTotal) * 100).toFixed(1)}% of ${d.yesterdayTotal})`
      );

    if (stateDetails.length > 0) {
      context += stateDetails.join(". ") + ". ";
    }

    context +=
      `This is a proxy signal — stations may stop reporting for reasons other ` +
      `than fuel unavailability (maintenance, system errors, temporary closure). ` +
      `The pattern across multiple stations is more informative than individual cases.`;
  }

  context +=
    ` Coverage: WA (FuelWatch, fully transparent) + NSW (FuelCheck, CKAN open data). ` +
    `Other states lack public station-level reporting.`;

  // Value headline
  const value =
    stoppedCount === 0
      ? `${today.totalStations} reporting`
      : `${stoppedCount} stopped reporting`;

  return {
    label: "Station availability",
    value,
    trend,
    source: `FuelWatch WA + FuelCheck NSW — ${today.date}`,
    sourceUrl: "https://www.fuelwatch.wa.gov.au/",
    context,
    lastUpdated: today.generated,
    automated: true,
    layer: 4,
    layerLabel: "Retail impact",
    propagatesTo:
      "Station closures compound panic buying and increase travel distance for remaining supply",
    components: components.length > 0 ? components : undefined,
  };
}
