/**
 * Station Availability — Gap Detection Proxy Signal
 *
 * Compares consecutive daily station snapshots to detect stations that
 * stopped reporting. A station present yesterday but absent today is
 * "not reporting" — a proxy for potentially being out of fuel.
 *
 * This is a structural proxy, not a confirmed outage count. Stations
 * may stop reporting for other reasons (maintenance, system errors,
 * temporary closure). The signal is most useful in aggregate and in
 * the context of other supply chain signals.
 *
 * Data sources:
 *   - WA FuelWatch (daily, ~1,100 stations across diesel + petrol)
 *   - NSW FuelCheck (daily, ~5,600 stations across diesel + petrol)
 *
 * Snapshot files: app/src/data/station-snapshots/YYYY-MM-DD.json
 * Generated by: scripts/snapshot-stations.mjs (runs in daily launchd agent)
 */

import { readFileSync, readdirSync } from "fs";
import path from "path";
import type { Signal, SignalComponent } from "./types";

const SNAPSHOT_DIR = path.join(
  process.cwd(),
  "src",
  "data",
  "station-snapshots"
);

interface StationRecord {
  id: string;
  state: string;
  source: string;
  product: string;
  brand: string | null;
  name: string;
  location: string;
  price: number;
}

interface Snapshot {
  date: string;
  generated: string;
  sources: {
    wa_fuelwatch: { diesel: number; petrol: number };
    nsw_fuelcheck: { diesel: number; petrol: number };
  };
  totalStations: number;
  stations: StationRecord[];
}

function loadSnapshot(filename: string): Snapshot | null {
  try {
    const filePath = path.join(SNAPSHOT_DIR, filename);
    const raw = readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as Snapshot;
  } catch {
    return null;
  }
}

function getSnapshotFiles(): string[] {
  try {
    return readdirSync(SNAPSHOT_DIR)
      .filter((f) => f.match(/^\d{4}-\d{2}-\d{2}\.json$/))
      .sort()
      .reverse(); // newest first
  } catch {
    return [];
  }
}

interface GapAnalysis {
  today: Snapshot;
  yesterday: Snapshot;
  stoppedReporting: StationRecord[];
  newlyReporting: StationRecord[];
  byState: Record<string, { stopped: number; new: number; todayTotal: number; yesterdayTotal: number }>;
  byProduct: Record<string, { stopped: number; new: number }>;
}

function analyseGaps(today: Snapshot, yesterday: Snapshot): GapAnalysis {
  const todayIds = new Set(today.stations.map((s) => s.id));
  const yesterdayIds = new Set(yesterday.stations.map((s) => s.id));
  const yesterdayById = new Map(yesterday.stations.map((s) => [s.id, s]));
  const todayById = new Map(today.stations.map((s) => [s.id, s]));

  const stoppedReporting: StationRecord[] = [];
  const newlyReporting: StationRecord[] = [];

  for (const id of yesterdayIds) {
    if (!todayIds.has(id)) {
      stoppedReporting.push(yesterdayById.get(id)!);
    }
  }

  for (const id of todayIds) {
    if (!yesterdayIds.has(id)) {
      newlyReporting.push(todayById.get(id)!);
    }
  }

  // Breakdown by state
  const byState: Record<string, { stopped: number; new: number; todayTotal: number; yesterdayTotal: number }> = {};
  for (const s of stoppedReporting) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].stopped++;
  }
  for (const s of newlyReporting) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].new++;
  }
  for (const s of today.stations) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].todayTotal++;
  }
  for (const s of yesterday.stations) {
    if (!byState[s.state]) byState[s.state] = { stopped: 0, new: 0, todayTotal: 0, yesterdayTotal: 0 };
    byState[s.state].yesterdayTotal++;
  }

  // Breakdown by product
  const byProduct: Record<string, { stopped: number; new: number }> = {};
  for (const s of stoppedReporting) {
    if (!byProduct[s.product]) byProduct[s.product] = { stopped: 0, new: 0 };
    byProduct[s.product].stopped++;
  }
  for (const s of newlyReporting) {
    if (!byProduct[s.product]) byProduct[s.product] = { stopped: 0, new: 0 };
    byProduct[s.product].new++;
  }

  return { today, yesterday, stoppedReporting, newlyReporting, byState, byProduct };
}

export function fetchStationAvailability(): Signal | null {
  const files = getSnapshotFiles();
  if (files.length === 0) return null;

  const today = loadSnapshot(files[0]);
  if (!today) return null;

  const waTotal =
    today.sources.wa_fuelwatch.diesel + today.sources.wa_fuelwatch.petrol;
  const nswTotal =
    today.sources.nsw_fuelcheck.diesel + today.sources.nsw_fuelcheck.petrol;

  // Use unique IDs for the station count — historical snapshots may have
  // inflated totalStations due to duplicate records. (SPEC-005 R2)
  const uniqueStationCount = new Set(today.stations.map((s) => s.id)).size;

  // Always show monitoring coverage as components
  const components: SignalComponent[] = [
    {
      label: "WA stations",
      value: `${waTotal.toLocaleString()} reporting`,
      change: `${today.sources.wa_fuelwatch.diesel} diesel, ${today.sources.wa_fuelwatch.petrol} petrol`,
      trend: "stable",
    },
    {
      label: "NSW stations",
      value: `${nswTotal.toLocaleString()} reporting`,
      change: `${today.sources.nsw_fuelcheck.diesel} diesel, ${today.sources.nsw_fuelcheck.petrol} petrol`,
      trend: "stable",
    },
  ];

  // If we only have one snapshot, report coverage (no gap data yet)
  if (files.length < 2) {
    return {
      label: "Fuel station monitoring",
      value: `${uniqueStationCount.toLocaleString()} stations tracked daily`,
      trend: "stable",
      source: `FuelWatch WA + FuelCheck NSW — ${today.date}`,
      sourceUrl: "https://www.fuelwatch.wa.gov.au/",
      context:
        `We monitor ${uniqueStationCount.toLocaleString()} fuel stations daily across WA and NSW ` +
        `— the only two states with fully transparent, public station-level price feeds. ` +
        `Victoria, Queensland, South Australia, Tasmania, NT, and ACT do not publish station-level data. ` +
        `Gap detection (stations that stop appearing in the feed) activates after the second daily snapshot.`,
      lastUpdated: today.generated,
      automated: true,
      layer: 4,
      layerLabel: "Retail impact",
      propagatesTo:
        "Station closures compound panic buying and increase travel distance for remaining supply",
      components,
    };
  }

  const yesterday = loadSnapshot(files[1]);
  if (!yesterday) return null;

  const gaps = analyseGaps(today, yesterday);
  const stoppedCount = gaps.stoppedReporting.length;
  const newCount = gaps.newlyReporting.length;

  // Trend based on net disappearances.
  // Use unique IDs as denominator, not raw totalStations, so the
  // threshold is reachable with realistic disappearance counts. (SPEC-005 R2)
  const yesterdayUniqueCount = new Set(yesterday.stations.map((s) => s.id)).size;
  const stoppedPct = yesterdayUniqueCount > 0
    ? (stoppedCount / yesterdayUniqueCount) * 100
    : 0;
  const trend: Signal["trend"] =
    stoppedPct > 5
      ? "critical"
      : stoppedPct > 2
        ? "up"
        : stoppedCount > newCount
          ? "up"
          : "stable";

  // Add gap detection results to components
  for (const [state, data] of Object.entries(gaps.byState)) {
    // Update existing state component with gap data
    const existing = components.find((c) => c.label === `${state} stations`);
    if (existing && data.stopped > 0) {
      existing.change = `${data.stopped} dropped from feed`;
      existing.trend = data.stopped > data.new ? "up" : "stable";
    }
  }

  // Product-level gaps
  for (const [product, data] of Object.entries(gaps.byProduct)) {
    if (data.stopped > 0) {
      components.push({
        label: `${product.charAt(0).toUpperCase() + product.slice(1)}`,
        value: `${data.stopped} disappeared`,
        change: data.new > 0 ? `${data.new} returned` : undefined,
        trend: data.stopped > 5 ? "up" : "stable",
      });
    }
  }

  // Build context — lead with what we can see, then name the gap
  let context: string;

  if (stoppedCount === 0) {
    context =
      `All ${uniqueStationCount.toLocaleString()} monitored stations still appearing in public feeds ` +
      `between ${yesterday.date} and ${today.date}. ` +
      `This means no stations dropped out of the feed entirely — ` +
      `but stations can be out of fuel and still appear in price data. ` +
      `Actual outage numbers are higher than what feed monitoring alone can detect.`;
  } else {
    context =
      `${stoppedCount} station${stoppedCount !== 1 ? "s" : ""} dropped from public feeds ` +
      `between ${yesterday.date} and ${today.date}. `;

    if (newCount > 0) {
      context += `${newCount} returned. `;
    }

    context +=
      `Feed disappearances are a floor, not a ceiling — ` +
      `stations can be out of fuel and still appear in price data.`;
  }

  context +=
    ` Only WA and NSW publish station-level data. ` +
    `Victoria, Queensland, SA, Tasmania, NT, and ACT have no public station-level feeds ` +
    `— outages in those states are invisible to independent monitoring.`;

  // Value headline — lead with monitoring scale, flag gaps if any
  const value =
    stoppedCount === 0
      ? `${uniqueStationCount.toLocaleString()} stations tracked — no feed dropouts`
      : `${stoppedCount} station${stoppedCount !== 1 ? "s" : ""} dropped from feed — ${uniqueStationCount.toLocaleString()} tracked`;

  return {
    label: "Fuel station monitoring",
    value,
    trend,
    source: `FuelWatch WA + FuelCheck NSW — ${today.date}`,
    sourceUrl: "https://www.fuelwatch.wa.gov.au/",
    context,
    lastUpdated: today.generated,
    automated: true,
    layer: 4,
    layerLabel: "Retail impact",
    propagatesTo:
      "Station closures compound panic buying and increase travel distance for remaining supply",
    components,
    secondary: {
      label: "Transparency gap",
      value: "6 states and territories publish no station-level data",
      detail:
        "The government announced a national outage dashboard is 'under preparation'. " +
        "This data has always existed — WA and NSW already publish it. " +
        "The gap is political, not technical.",
    },
  };
}
